{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n"
     ]
    }
   ],
   "source": [
    "import bot\n",
    "import warnings\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "\n",
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-05-10 17:10:17,537 (util.py:68 PollingThread) ERROR - TeleBot: \"ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\\n[b\\'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}\\']',)\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\util.py\", line 62, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\__init__.py\", line 281, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\__init__.py\", line 251, in get_updates\n",
      "    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 199, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 65, in _make_request\n",
      "    return _check_result(method_name, result)['result']\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 84, in _check_result\n",
      "    raise ApiException(msg, method_name, result)\n",
      "telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\n",
      "\"\n",
      "2020-05-10 17:10:17,546 (__init__.py:443 MainThread) ERROR - TeleBot: \"A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\"\n",
      "2020-05-10 17:10:21,427 (util.py:68 PollingThread) ERROR - TeleBot: \"ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\\n[b\\'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}\\']',)\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\util.py\", line 62, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\__init__.py\", line 281, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\__init__.py\", line 251, in get_updates\n",
      "    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 199, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 65, in _make_request\n",
      "    return _check_result(method_name, result)['result']\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 84, in _check_result\n",
      "    raise ApiException(msg, method_name, result)\n",
      "telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\n",
      "\"\n",
      "2020-05-10 17:10:21,428 (__init__.py:443 MainThread) ERROR - TeleBot: \"A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\"\n",
      "2020-05-10 17:10:25,253 (util.py:68 PollingThread) ERROR - TeleBot: \"ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\\n[b\\'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}\\']',)\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\util.py\", line 62, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\__init__.py\", line 281, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\__init__.py\", line 251, in get_updates\n",
      "    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 199, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 65, in _make_request\n",
      "    return _check_result(method_name, result)['result']\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 84, in _check_result\n",
      "    raise ApiException(msg, method_name, result)\n",
      "telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\n",
      "\"\n",
      "2020-05-10 17:10:25,255 (__init__.py:443 MainThread) ERROR - TeleBot: \"A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\"\n",
      "2020-05-10 17:10:29,569 (util.py:68 PollingThread) ERROR - TeleBot: \"ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\\n[b\\'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}\\']',)\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\util.py\", line 62, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\__init__.py\", line 281, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\__init__.py\", line 251, in get_updates\n",
      "    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 199, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 65, in _make_request\n",
      "    return _check_result(method_name, result)['result']\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 84, in _check_result\n",
      "    raise ApiException(msg, method_name, result)\n",
      "telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\n",
      "\"\n",
      "2020-05-10 17:10:29,570 (__init__.py:443 MainThread) ERROR - TeleBot: \"A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\"\n",
      "2020-05-10 17:10:35,164 (util.py:68 PollingThread) ERROR - TeleBot: \"ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\\n[b\\'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}\\']',)\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\util.py\", line 62, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\__init__.py\", line 281, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\__init__.py\", line 251, in get_updates\n",
      "    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 199, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 65, in _make_request\n",
      "    return _check_result(method_name, result)['result']\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 84, in _check_result\n",
      "    raise ApiException(msg, method_name, result)\n",
      "telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\n",
      "\"\n",
      "2020-05-10 17:10:35,165 (__init__.py:443 MainThread) ERROR - TeleBot: \"A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\"\n",
      "2020-05-10 17:10:42,489 (util.py:68 PollingThread) ERROR - TeleBot: \"ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\\n[b\\'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}\\']',)\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\util.py\", line 62, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\__init__.py\", line 281, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\__init__.py\", line 251, in get_updates\n",
      "    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 199, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 65, in _make_request\n",
      "    return _check_result(method_name, result)['result']\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 84, in _check_result\n",
      "    raise ApiException(msg, method_name, result)\n",
      "telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\n",
      "\"\n",
      "2020-05-10 17:10:42,491 (__init__.py:443 MainThread) ERROR - TeleBot: \"A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\"\n",
      "2020-05-10 17:10:54,054 (util.py:68 PollingThread) ERROR - TeleBot: \"ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\\n[b\\'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}\\']',)\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\util.py\", line 62, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\__init__.py\", line 281, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\__init__.py\", line 251, in get_updates\n",
      "    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 199, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 65, in _make_request\n",
      "    return _check_result(method_name, result)['result']\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 84, in _check_result\n",
      "    raise ApiException(msg, method_name, result)\n",
      "telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\n",
      "\"\n",
      "2020-05-10 17:10:54,055 (__init__.py:443 MainThread) ERROR - TeleBot: \"A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\"\n",
      "2020-05-10 17:11:14,131 (util.py:68 PollingThread) ERROR - TeleBot: \"ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\\n[b\\'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}\\']',)\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\util.py\", line 62, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\__init__.py\", line 281, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\__init__.py\", line 251, in get_updates\n",
      "    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 199, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 65, in _make_request\n",
      "    return _check_result(method_name, result)['result']\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 84, in _check_result\n",
      "    raise ApiException(msg, method_name, result)\n",
      "telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\n",
      "\"\n",
      "2020-05-10 17:11:14,133 (__init__.py:443 MainThread) ERROR - TeleBot: \"A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\"\n",
      "2020-05-10 17:11:49,449 (util.py:68 PollingThread) ERROR - TeleBot: \"ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\\n[b\\'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}\\']',)\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\util.py\", line 62, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\__init__.py\", line 281, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\__init__.py\", line 251, in get_updates\n",
      "    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 199, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 65, in _make_request\n",
      "    return _check_result(method_name, result)['result']\n",
      "  File \"c:\\users\\mkapchenko\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\telebot\\apihelper.py\", line 84, in _check_result\n",
      "    raise ApiException(msg, method_name, result)\n",
      "telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\n",
      "\"\n",
      "2020-05-10 17:11:49,451 (__init__.py:443 MainThread) ERROR - TeleBot: \"A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\"\n"
     ]
    }
   ],
   "source": [
    "bot.bot.polling(none_stop=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
